#!/bin/bash

# Function to modify the .m3u8 file
modify_m3u8() {
    # Add a delay to ensure the file write is complete
    sleep 0.2
    # Modify the .m3u8 file
    sed -i '/\.ts$/s|^|play/|' output.m3u8
}

# Initialize timestamp variable
timestamp=$(stat -c %Y output.m3u8 2>/dev/null)

# Run the FFmpeg command for screen recording and webcam recording
ffmpeg -f x11grab -r 30 -s 1920x1080 -i :0.0 -f v4l2 -video_size 640x480 -i /dev/video0 -filter_complex "[1:v]scale=320:-1[webcam];[0:v][webcam]overlay=W-w-10:H-h-10:format=rgb" -c:v libx264 -preset ultrafast -g 60 -sc_threshold 0 -f tee "[f=hls:hls_time=1:hls_list_size=5:hls_flags=delete_segments+temp_file:hls_segment_filename=play/output%03d.ts]output.m3u8|[f=mp4]output.mp4" &

# Store its PID
PID=$!

# Set up trap to modify the .m3u8 file before script exit
trap 'modify_m3u8' EXIT

# Monitor the .m3u8 file and replace lines as needed
while { kill -0 $PID || let count++; (( count < 5 )); } 2> /dev/null; do
    # Check if the .m3u8 file has been modified
    if [[ $(stat -c %Y output.m3u8) -gt $timestamp ]]; then
        modify_m3u8
        # Update the timestamp
        timestamp=$(stat -c %Y output.m3u8)
    fi
    sleep 0.2
done
